apiVersion: apps/v1
kind: Deployment
metadata:
  name: JavaProject-deploy
  labels:
    app: JavaProject-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: JavaProject-app
  template:
    metadata:
      labels:
        app: JavaProject-app
    spec:
      containers:
      - name: JavaProject-container
        image: JavaProject/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: JavaProject-np-service
  labels:
    app: JavaProject-np-app
spec:
  selector:
    app: JavaProject-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
